title: Japanese Audio Emotion Recognition
remote_theme: hydecorp/hydejack

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(67,83,106)

# file: _config.yml
author:
  social:
    github:  https://github.com/AtomScott/japanese-audio-emotion

paginate:      5
paginate_path: /blog/page-:num/
